- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: config for chosts
  template:
    src: "site.conf.j2"
    dest: "/etc/nginx/conf.d/site-{{ item }}.conf"
  loop: "{{ sites }}"
  notify: restart nginx

- name: Create folders for sites
  file: 
    path: "/var/www/{{ item }}"
    state: directory
  loop: "{{ sites }}"

- name: Copy indeces from templates
  template:
    src: 'index.html.j2'
    dest: "/var/www/{{ item }}/index.html"
    owner: root
    group: root
    mode: 0644
  loop: "{{ sites }}"
    
